language: node_js
node_js:
    - '8.11'

cache:
  yarn: true

env:
  global:
    # build number used by blt pipeline
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    # allows `make` commands to run in parallel - Travis provides '2' cores
    # - MAKEFLAGS="-j2"  Disabling for now because of mess it can make
    # current time
    - DATETIME=$(date +%s)
    # Travis build url
    - TRAVIS_BUILD_URL=https://travis-ci.com/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID

before_install:
  # install more recent `yarn`
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn --version

script:
  - docker build -t test .
